# Generated by Django 4.2.6 on 2023-12-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_protocole_servico_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
    ]
